### ISSUE TITLE
i keep getting this error whenever i want to train with my own dataset

### ISSUE THREAD

**Issue by ebukaoguchi** [thatbrguy/Dehaze-GAN#10]
C:\Users\asus\Miniconda3\envs\Dehaze-GAN-master\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 64441 --file C:/Users/asus/Dehaze-GAN-master/Dehaze-GAN-master/main.py --A_dir A --B_dir B --batch_size 1 --epochs 20
pydev debugger: process 7076 is connecting

Connected to pydev debugger (build 192.7142.56)
Loading Model
Model Loaded
Loading Data
(2170, 256, 256, 3) (384, 256, 256, 3)
C:\Users\asus\Dehaze-GAN-master\Dehaze-GAN-master
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\helpers\pydev\pydevd.py", line 1415, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/asus/Dehaze-GAN-master/Dehaze-GAN-master/main.py", line 60, in <module>
    net.train()
  File "C:\Users\asus\Dehaze-GAN-master\Dehaze-GAN-master\model.py", line 258, in train
    self.B_train[i] = cv2.imread(os.path.join(os.getcwd(), self.B_dir, file), 1).astype(np.float32)
AttributeError: 'NoneType' object has no attribute 'astype'

Process finished with exit code 1

**Comment by thatbrguy** [comment]
Sorry for the late response. Your error could mean that your image is not located in the path used in `cv2.imread`. The function returns `None` if the image is not found in the given path (else, it would have returned an array of the image).
