### ISSUE TITLE
When I run main.py and replicating.py, I meet a same error.

### ISSUE THREAD

**Issue by andongBlue** [thatbrguy/Dehaze-GAN#7]
When I run main.py and replicating.py, I meet a same error.
The error may be about allow_pickle=False.
We can see the following tips ,there is 'error' in the last line.
`WARNING:tensorflow:From /home/hp/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/initializers.py:104: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with distribution=normal is deprecated and will be removed in a future version.
Instructions for updating:
`normal` is a deprecated alias for `truncated_normal`
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    net.train()
  File "/home/hp/下载/Dehaze-GAN-master/model.py", line 230, in train
    self.build_model()
  File "/home/hp/下载/Dehaze-GAN-master/model.py", line 167, in build_model
    self.RealB_VGG = self.build_vgg(self.RealB)
  File "/home/hp/下载/Dehaze-GAN-master/model.py", line 141, in build_vgg
    model = vgg19.Vgg19()
  File "/home/hp/下载/Dehaze-GAN-master/vgg19.py", line 13, in __init__
    self.data_dict = np.load('./vgg19.npy', encoding='latin1').item()
  File "/home/hp/anaconda3/envs/tensorflow/lib/python3.6/site-packages/numpy/lib/npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/hp/anaconda3/envs/tensorflow/lib/python3.6/site-packages/numpy/lib/format.py", line 692, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
`

**Comment by andongBlue** [comment]
I think I may ask a XYproblem.
When I run main.py and replicating.py,I can't load the file of npy.
How can I fix it?

**Comment by BITWN** [comment]
I met the same problem, have you solved it?

**Comment by Fu7388** [comment]
I think you'd better to degrade numpy version.
pip install numpy ==1.16.0.
